### ISSUE TITLE
Cell weights description does not make sense

### ISSUE THREAD

**Issue by krisdavis** [ubcgif/DCIPoctree#3]
In the input file, there is this:
7 | Cell Weights | additional cell weights
8 | Face Weights | additional face weights
9 | Face Weights | additional face weights

Is the first one "global" weights?

**Comment by dccowan** [comment]
Hi @krisdavis the order is:

global cell weights
global face weights
additional cell weight only in smallness term.

Where did you find the typo?

**Comment by krisdavis** [comment]
Thanks @dccowan. It's on this page:
https://dcipoctree.readthedocs.io/en/latest/content/inputfiles/dcinversion.html
Although if I would have read the detailed descriptions, I would have seen it. 
![image](https://user-images.githubusercontent.com/10675064/87155296-95e20f00-c26f-11ea-920d-c1e06f308f67.png)

**Comment by dccowan** [comment]
@krisdavis The description of the weights in the DC and IP input files has been updated.
